### ISSUE TITLE
log() instead of debug_()

### ISSUE THREAD

**Issue by zoujiaqing** [andrewlalis/slf4d#1]

**Comment by andrewlalis** [comment]
Can you elaborate a bit more on your issue? Because I'm fairly certain you can still call `log(...)`, but then you need to provide the logging level yourself.

**Comment by andrewlalis** [comment]
Okay, just looked, and `log` is already a function, defined here: https://andrewlalis.github.io/slf4d/guide/using-slf4d.html#logging-functions

I'll close this as "Won't do", but re-open or make a new issue with more context if that isn't want you mean.
