### ISSUE TITLE
logF fails even if there's no string format specifier

### ISSUE THREAD

**Issue by AndrejMitrovic** [andrewlalis/slf4d#2]
I'd like to use `logF` consistently in my codebase but this isn't always possible because of one edge-case. Here's a few examples:

```D
// fails to compile (this is fine)
logF!("Wrong %s")(Levels.INFO);

// compiles
logF!("Okay %s")(Levels.INFO, "okay");

// fails: Orphan format arguments: args[0..5]
logF!("Okay")(Levels.INFO);
```

I think the last case could compile unless it's really difficult to support this use-case in the library.

There's already a precedent for this as the following Phobos code compiles:

```D
import std.stdio;
import std.format;

void main() {
    writeln(format!("Hello"));
}
```

Alternatively for now I'll do either of:

```D
log(Levels.INFO, "Okay")
logF!("%s")(Levels.INFO, "Okay")
```

----

By the way thanks a lot for building slf4d! I've used slf4j in Java projects and it's nice to have an equivalent in D. 🙂

**Comment by andrewlalis** [comment]
Should be fixed in version `2.4.1`. I really should add more comprehensive testing, if I could find the time...
