### ISSUE TITLE
Unable to build config library

### ISSUE THREAD

**Issue by goliath29** [andrewlalis/slf4d#4]
When attempting to run an install for pyprovision, I face the below error.

```      slf4d 2.4.3: building configuration "library"...
      ../../.dub/packages/slf4d-2.4.3/slf4d/source/slf4d/default_provider/factory.d(34,22): Error: non-shared method `core.sync.rwmutex.ReadWriteMutex.this` is not callable using a `shared` object
      /usr/lib/ldc/x86_64-linux-gnu/include/d/core/sync/rwmutex.d(89,5):        Consider adding `shared` here
      ../../.dub/packages/slf4d-2.4.3/slf4d/source/slf4d/default_provider/factory.d(43,22): Error: non-shared method `core.sync.rwmutex.ReadWriteMutex.writer` is not callable using a `shared` object
      /usr/lib/ldc/x86_64-linux-gnu/include/d/core/sync/rwmutex.d(148,22):        Consider adding `shared` here
      ../../.dub/packages/slf4d-2.4.3/slf4d/source/slf4d/default_provider/factory.d(63,22): Error: non-shared method `core.sync.rwmutex.ReadWriteMutex.writer` is not callable using a `shared` object
      /usr/lib/ldc/x86_64-linux-gnu/include/d/core/sync/rwmutex.d(148,22):        Consider adding `shared` here
      ../../.dub/packages/slf4d-2.4.3/slf4d/source/slf4d/default_provider/factory.d(96,22): Error: non-shared method `core.sync.rwmutex.ReadWriteMutex.reader` is not callable using a `shared` object
      /usr/lib/ldc/x86_64-linux-gnu/include/d/core/sync/rwmutex.d(136,22):        Consider adding `shared` here
      /usr/bin/ldc2 failed with exit code 1.
      error: command '/usr/bin/dub' failed with exit code 2
      [end of output]
``` 

I have update ldc2 on my computer itself, and on my Ubuntu terminal, and am still unable to proceed with the install.
Is there any solution or fix I can perform to allow for the install?

**Comment by andrewlalis** [comment]
It looks like this error is related to SLF4D itself, not this particular provider implementation for the DLog logging system. I will transfer your issue to that repository.

**Comment by andrewlalis** [comment]
@goliath29 what LDC version are you using, specifically? I have compiled with 1.33.0 for linux x86_64, and it does indeed compile. I've also run the CI pipeline with the latest ubuntu version, and latest DMD and LDC, for which all runs are successful.

**Comment by goliath29** [comment]
I am currently running LDC 1.36.0

**Comment by andrewlalis** [comment]
I have a suspicion that the issue may be related to line 68 of Provision's [dub.sdl](https://github.com/Dadoum/Provision/blob/main/dub.sdl), which is `dflags "--link-defaultlib-shared=false" platform="ldc"`. I suppose that this might be forcing the standard lib to not be assumed as shared, which then causes conflict with SLF4D because my library does use shared semantics.

In the short term, I don't have time to work on this, so maybe experiment and see if you can disable that flag in whatever you're using. In the long term though, D's `shared` semantics are a pain, and I'll refactor SLF4D at some point to get rid of them.

**Comment by andrewlalis** [comment]
@goliath29 I have upgraded to remove all usage of `shared`, and integrated the changes into the latest handy-httpd release (which is what your dependency, provision, uses), so I suggest prompting the author of the provision software to update to SLF4D v3.0.0 and Handy-Httpd v8.2.0.
